# Generated by Django 5.2.8 on 2025-12-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVoiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('voice_model_file', models.FileField(help_text='The file is binary and permanent, model Ia learned (.pth, .pt, .zip)', upload_to='voice_models/', verbose_name='Model Voz file (IA)')),
                ('sample_audio', models.FileField(blank=True, help_text='Reference audio (ogg/mp3) used to train or demonstration.', null=True, upload_to='sample_audios/', verbose_name='Original audio sample')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Voice Model',
                'verbose_name_plural': 'Custom Voice Models',
            },
        ),
    ]
