# Generated by Django 5.2.9 on 2025-12-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customvoicemodel',
            name='sample_audio',
            field=models.FileField(help_text='Reference audio (ogg/mp3) used to train or demonstration.', upload_to='sample_audios/', verbose_name='Original audio sample'),
        ),
    ]
