# Generated by Django 5.2.9 on 2025-12-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customvoicemodel_sample_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customvoicemodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Processamento Pendente'), ('COMPLETED', 'Concluído'), ('FAILED', 'Falha no Processamento')], default='PENDING', max_length=10, verbose_name='Status de Processamento'),
        ),
        migrations.AlterField(
            model_name='customvoicemodel',
            name='voice_model_file',
            field=models.FileField(blank=True, help_text='The file is binary and permanent, model Ia learned (.pth, .pt, .zip)', null=True, upload_to='voice_models/', verbose_name='Model Voz file (IA)'),
        ),
    ]
